# 这是SpineWallpaper的配置文件，必须放置在SpineWallpaper.exe旁边才能被读取

# 指定一个目录下的Spine导出文件，支持json格式
spine_file=D:\Wallpapers\MySpine\character.json

# 指定一个动画文件
animation=idle

# 是否对图片启用通道或Alpha预乘处理。
# 设置窗口选择“按配置”时读取这里；省略对应配置项则按关闭处理。
force_premultiplied_channel=true
force_premultiplied_alpha=true

# 壁纸相对屏幕中心的偏移，单位为像素；向右和向下为正，向左和向上为负。
offset_x=0
offset_y=0

# 壁纸缩放比例；1.0 为原始大小，0.5 为缩小一半，2.0 为放大一倍。
scale=1.0
